# Travis config for EMA workbench
language: python
sudo: true

python:
- "3.7"
- "3.8-dev"

env:
- DEPS="numpy matplotlib pandas jupyter ipyparallel nose scikit-learn mock seaborn statsmodels"

services:
- xvfb

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install -c conda conda-env
- conda update -q conda --no-deps
- conda info -a # Useful for debugging any issues with conda
- conda install --yes $DEPS # Replace dep1 dep2 ... with your dependencies
- pip install zmq # zmq is not available via conda for some reason
- pip install pydotplus
- pip install coveralls
- pip install pysd
- pip install nose-exclude
- pip install salib
- pip install future
# jpype installation code to be added

before_install:
- "export DISPLAY=:99.0"

script:
- nosetests --exclude-dir=./test/test_connectors --with-coverage --verbose --cover-package=ema_workbench.em_framework --cover-package=ema_workbench.util --cover-package=ema_workbench.analysis


# coverage needs to be added
after_success:
- coveralls

#notifications:
#email: false